const LOADING = 'LOADING';
const GET_PROFILE = 'GET_PROFILE';
const ERROR = 'ERROR';
const TAB_SELECT = 'TAB_SELECT';
const INPUT_SEARCH = 'INPUT_SEARCH';
const SUBMIT_FORM = 'SUBMIT_FORM';
const TABLE_INFO = 'TABLE_INFO';

export { 
  LOADING, 
  GET_PROFILE, 
  ERROR,
  TAB_SELECT,
  INPUT_SEARCH,
  SUBMIT_FORM,
  TABLE_INFO
 };
 