const LOADING = 'LOADING';
const GET_PROFILE = 'GET_PROFILE';
const ERROR = 'ERROR';
const POST_DATA = 'POST_DATA';
const TAB_SELECT = 'TAB_SELECT';
const INPUT_SEARCH = 'INPUT_SEARCH';
const SUBMIT_FORM = 'SUBMIT_FORM';
const TABLE_INFO = 'TABLE_INFO';
const MODAL_STATUS = 'MODAL_STATUS';
const MODAL_INPUT = 'MODAL_INPUT';
const MODAL_SUBMIT = 'MODAL_SUBMIT';

export { 
  LOADING, 
  GET_PROFILE, 
  ERROR,
  TAB_SELECT,
  INPUT_SEARCH,
  SUBMIT_FORM,
  TABLE_INFO,
  MODAL_STATUS,
  MODAL_INPUT,
  MODAL_SUBMIT,
  POST_DATA 
 };
 